# Generated by Django 2.2.7 on 2020-01-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('idsel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=90)),
                ('cbarras', models.CharField(max_length=50)),
                ('cbarras2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=2)),
                ('estanteria', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=255)),
                ('pacto', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('dc', models.CharField(max_length=2)),
                ('gfh', models.CharField(max_length=8)),
                ('disp', models.CharField(max_length=6)),
            ],
        ),
    ]
