# Generated by Django 2.2.7 on 2020-01-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gfhs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gfh', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5)),
                ('gfh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.gfhs')),
            ],
        ),
    ]
