# Generated by Django 2.2.7 on 2020-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_dispositivos_gfhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='idsel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='nombre',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='gfhs',
            name='gfh',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='gfhs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterIndexTogether(
            name='configurations',
            index_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp')},
        ),
    ]
