# Generated by Django 2.2.7 on 2020-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20200211_2153'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulos',
            name='restArticulos',
        ),
        migrations.AddConstraint(
            model_name='articulos',
            constraint=models.UniqueConstraint(fields=('codigo', 'hospital'), name='rarticulos'),
        ),
    ]
