# Generated by Django 2.2.7 on 2020-02-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_auto_20200211_2207'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulos',
            name='rarticulos',
        ),
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together={('codigo', 'hospital')},
        ),
    ]
