# Generated by Django 2.2.7 on 2020-01-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_auto_20200125_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp')},
        ),
        migrations.AlterIndexTogether(
            name='configurations',
            index_together=set(),
        ),
    ]
