# Generated by Django 2.2.7 on 2020-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_auto_20200211_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='hospital',
            field=models.IntegerField(),
        ),
    ]
