# Generated by Django 2.2.7 on 2020-02-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_auto_20200211_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
        ),
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together=set(),
        ),
    ]
