# Generated by Django 2.2.7 on 2020-02-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_auto_20200211_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='hospital',
        ),
    ]
