# Generated by Django 2.2.7 on 2020-01-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20200125_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='gfh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs'),
        ),
    ]
