# Generated by Django 2.2.7 on 2020-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_auto_20200125_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
