# Generated by Django 2.2.7 on 2020-01-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0010_auto_20200125_1849'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together=set(),
        ),
    ]
