# Generated by Django 3.0.6 on 2020-05-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0011_auto_20200317_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfhs',
            name='hosp_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
            preserve_default=False,
        ),
    ]
