# Generated by Django 2.2.7 on 2020-01-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0011_auto_20200125_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp')},
        ),
    ]
