# Generated by Django 3.0.6 on 2020-05-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0012_gfhs_hosp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gfhs',
            name='hosp_id',
        ),
        migrations.AddField(
            model_name='gfhs',
            name='hp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.hospitales'),
        ),
    ]
