# Generated by Django 2.2.7 on 2020-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0013_auto_20200125_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
