# Generated by Django 3.0.6 on 2020-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0013_auto_20200530_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfhs',
            name='hosp_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
