# Generated by Django 3.0.6 on 2020-05-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0014_auto_20200530_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfhs',
            name='hosp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
        ),
    ]
