# Generated by Django 2.2.7 on 2020-01-25 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0014_auto_20200125_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='minimo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='pacto',
            field=models.FloatField(),
        ),
    ]
