# Generated by Django 3.0.6 on 2020-05-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0015_auto_20200530_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfhs',
            name='hosp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.hospitales'),
        ),
    ]
