# Generated by Django 3.0.6 on 2020-05-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0016_auto_20200530_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gfhs',
            old_name='hosp_id',
            new_name='hp_id',
        ),
    ]
