# Generated by Django 2.2.7 on 2020-05-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='user',
        ),
        migrations.CreateModel(
            name='pedidos_ident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npedido', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuarios')),
            ],
        ),
    ]
