# Generated by Django 2.2.7 on 2020-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200525_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_ident',
            name='npedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='npedido',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
