# Generated by Django 3.0.6 on 2020-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200526_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_ident',
            name='pedido',
            field=models.CharField(max_length=12),
        ),
    ]
