# Generated by Django 3.0.6 on 2020-06-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0013_auto_20200602_2237'),
        ('pedidos', '0006_auto_20200527_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('user_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuarios')),
            ],
        ),
    ]
