# Generated by Django 3.0.6 on 2020-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedidos_dc'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos_ident_dc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
