# Generated by Django 3.0.6 on 2021-01-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0036_auto_20201213_2311'),
        ('pedidos', '0011_datos_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='addLineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('filaConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.configurations')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
            ],
        ),
    ]
