# Generated by Django 3.0.6 on 2021-01-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0036_auto_20201213_2311'),
        ('pedidos', '0012_addlineapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlineapedido',
            name='filaConfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.excel'),
        ),
    ]
