# Generated by Django 3.0.6 on 2021-01-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_addrefpedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addLineaPedido',
        ),
    ]
