# Generated by Django 3.0.6 on 2021-01-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0036_auto_20201213_2311'),
        ('pedidos', '0015_delete_addlineapedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_dc',
            name='gfh',
        ),
        migrations.RemoveField(
            model_name='pedidos_dc',
            name='hospital',
        ),
        migrations.AddField(
            model_name='pedidos_ident_dc',
            name='disp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos_ident_dc',
            name='gfh',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos_ident_dc',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
            preserve_default=False,
        ),
    ]
