# Generated by Django 3.0.6 on 2021-01-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0036_auto_20201213_2311'),
        ('pedidos', '0017_auto_20210117_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='hospital',
        ),
        migrations.AddField(
            model_name='pedidos_ident',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
            preserve_default=False,
        ),
    ]
