# Generated by Django 3.0.6 on 2021-02-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('rutaFotos', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=15, null=True)),
                ('latitud', models.CharField(blank=True, max_length=15, null=True)),
                ('comentario', models.TextField(blank=True, max_length=1024, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='articulos/')),
            ],
        ),
        migrations.CreateModel(
            name='gfhs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gfh', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('hp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.hospitales')),
            ],
            options={
                'unique_together': {('gfh', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=6, unique=True)),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
            ],
            options={
                'unique_together': {('nombre', 'gfh')},
            },
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('idsel', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=90)),
                ('cbarras', models.CharField(max_length=50, null=True)),
                ('cbarras2', models.CharField(max_length=50, null=True)),
                ('foto', models.ImageField(upload_to='articulos/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
            ],
            options={
                'unique_together': {('codigo', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=2)),
                ('estanteria', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=6)),
                ('pacto', models.FloatField()),
                ('minimo', models.FloatField()),
                ('dc', models.CharField(max_length=2)),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
            ],
            options={
                'unique_together': {('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp')},
            },
        ),
        migrations.CreateModel(
            name='configurations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=2)),
                ('estanteria', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=6)),
                ('pacto', models.FloatField()),
                ('minimo', models.FloatField()),
                ('dc', models.CharField(max_length=2)),
                ('nconfig', models.IntegerField()),
                ('fechalta', models.DateTimeField(auto_now=True)),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
            ],
            options={
                'unique_together': {('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp', 'gfh', 'nconfig')},
            },
        ),
    ]
