# Generated by Django 3.0.6 on 2021-04-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20210220_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfhs',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
