# Generated by Django 2.2.7 on 2020-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20200211_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='cbarras',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='cbarras2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
