# Generated by Django 2.2.7 on 2020-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_auto_20200215_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfhs',
            name='gfh',
            field=models.CharField(max_length=4),
        ),
    ]
