# Generated by Django 2.2.7 on 2020-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20200218_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='codigo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='dispositivos',
            unique_together={('nombre', 'gfh')},
        ),
    ]
