# Generated by Django 2.2.7 on 2020-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0009_auto_20200309_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='foto',
            field=models.ImageField(upload_to='articulos'),
        ),
    ]
