# Generated by Django 2.2.7 on 2020-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0010_auto_20200315_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='foto',
            field=models.ImageField(upload_to='articulos/'),
        ),
    ]
