# Generated by Django 3.0.6 on 2020-05-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0011_auto_20200317_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfhs',
            name='hp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.hospitales'),
        ),
    ]
