# Generated by Django 3.0.6 on 2020-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0012_gfhs_hp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='nombre',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
