# Generated by Django 3.0.6 on 2020-11-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0016_auto_20201105_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='disp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='gfh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs'),
        ),
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp_id')},
        ),
    ]
