# Generated by Django 3.0.6 on 2020-11-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0017_auto_20201107_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp')},
        ),
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=2)),
                ('estanteria', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=6)),
                ('pacto', models.FloatField()),
                ('minimo', models.FloatField()),
                ('dc', models.CharField(max_length=2)),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
            ],
            options={
                'unique_together': {('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp')},
            },
        ),
    ]
