# Generated by Django 3.0.6 on 2020-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0018_auto_20201109_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='sesion',
            field=models.CharField(default=models.CharField(max_length=6), max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='disp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='excel',
            name='gfh',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='excel',
            name='hosp',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='excel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='excel',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
