# Generated by Django 3.0.6 on 2020-11-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0022_configurations_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='disp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos'),
        ),
        migrations.AlterField(
            model_name='excel',
            name='gfh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs'),
        ),
        migrations.AlterField(
            model_name='excel',
            name='hosp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
        ),
    ]
