# Generated by Django 3.0.6 on 2020-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0023_auto_20201112_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='fechalta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configurations',
            name='nconfig',
            field=models.CharField(default=0, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp', 'hosp', 'gfh', 'nconfig')},
        ),
        migrations.RemoveField(
            model_name='configurations',
            name='sesion',
        ),
    ]
