# Generated by Django 3.0.6 on 2020-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0025_auto_20201115_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitales',
            name='rutaFotos',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
