# Generated by Django 3.0.6 on 2020-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0026_hospitales_rutafotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='rutaFotos',
            field=models.CharField(default='', max_length=30),
        ),
    ]
