# Generated by Django 3.0.6 on 2020-11-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0027_auto_20201122_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='rutaFotos',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
