# Generated by Django 3.0.6 on 2020-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0028_auto_20201122_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='rutaFotos',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
