# Generated by Django 3.0.6 on 2021-02-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addRefPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=12)),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=100)),
                ('pacto', models.IntegerField()),
                ('dc', models.CharField(max_length=1)),
                ('gfh', models.CharField(max_length=4)),
                ('disp', models.CharField(max_length=6)),
                ('hospital', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='datos_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucorreo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ident', models.CharField(max_length=9, unique=True)),
                ('passwd', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pedidos_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
                ('user_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos_ident_dc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos_ident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos_dc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npedido', models.CharField(max_length=12)),
                ('cantidad', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npedido', models.CharField(max_length=12)),
                ('cantidad', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
            ],
        ),
    ]
