# Generated by Django 2.2.7 on 2020-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
