# Generated by Django 2.2.7 on 2020-05-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200517_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuarios'),
            preserve_default=False,
        ),
    ]
