# Generated by Django 2.2.7 on 2019-12-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacked', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='nombre_pagina',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datos',
            name='page',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='datos',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datos',
            name='titulo_cont',
            field=models.CharField(max_length=50),
        ),
    ]
