# Generated by Django 2.2.7 on 2020-02-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='articulos',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='articulos',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurations',
            name='hosp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together={('codigo', 'hospital')},
        ),
    ]
