# Generated by Django 2.2.7 on 2020-02-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_auto_20200215_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurations',
            unique_together={('modulo', 'estanteria', 'ubicacion', 'division', 'disp')},
        ),
    ]
