# Generated by Django 3.0.6 on 2020-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0015_auto_20201105_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='disp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='gfh',
            field=models.CharField(max_length=8),
        ),
    ]
