# Generated by Django 3.0.6 on 2020-11-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0019_auto_20201111_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.articulos'),
        ),
    ]
