# Generated by Django 3.0.6 on 2020-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0020_auto_20201111_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='sesion',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
