# Generated by Django 3.0.6 on 2020-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0031_auto_20201122_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='nconfig',
            field=models.IntegerField(),
        ),
    ]
