# Generated by Django 3.0.6 on 2020-11-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0032_auto_20201123_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='sesion',
        ),
    ]
