# Generated by Django 3.0.6 on 2020-12-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0033_remove_excel_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitales',
            name='foto',
            field=models.ImageField(default=None, upload_to='articulos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitales',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospitales',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gfhs',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
