# Generated by Django 3.0.6 on 2020-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0034_auto_20201211_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
