# Generated by Django 3.0.6 on 2020-12-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0035_auto_20201211_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitales',
            name='comentario',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hospitales',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
