# Generated by Django 3.0.6 on 2020-09-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones', '0013_auto_20200602_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prb', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('stock', models.FloatField()),
                ('dc', models.CharField(max_length=2)),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dispositivos')),
                ('gfh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.gfhs')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.hospitales')),
            ],
        ),
    ]
